#pragma once 

#include <windows.h>
#include "Graphics/GL/GLTypes.hh"

#ifndef GLLOAD
#define GLLOAD(procName, type) \
	do{ \
		(procName)= \
			reinterpret_cast<type>(wglGetProcAddress(#procName));\
		if (procName != nullptr) \
			std::cout << std::format("[{}][GL] Loaded {}\n", __PROJECT_NAME__, #procName); \
	}while(0)
#endif

namespace Rupture::Graphics::GL
{
	void LoadGL12()
	{
		GLLOAD(glDrawRangeElements, PFNGLDRAWRANGEELEMENTSPROC);
		GLLOAD(glTexImage3D, PFNGLTEXIMAGE3DPROC);
		GLLOAD(glTexSubImage3D, PFNGLTEXSUBIMAGE3DPROC);
		GLLOAD(glCopyTexSubImage3D, PFNGLCOPYTEXSUBIMAGE3DPROC);
	}

	void LoadGL13()
	{
		GLLOAD(glActiveTexture, PFNGLACTIVETEXTUREPROC);
		GLLOAD(glSampleCoverage, PFNGLSAMPLECOVERAGEPROC);
		GLLOAD(glCompressedTexImage3D, PFNGLCOMPRESSEDTEXIMAGE3DPROC);
		GLLOAD(glCompressedTexImage2D, PFNGLCOMPRESSEDTEXIMAGE2DPROC);
		GLLOAD(glCompressedTexImage1D, PFNGLCOMPRESSEDTEXIMAGE1DPROC);
		GLLOAD(glCompressedTexSubImage3D, PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC);
		GLLOAD(glCompressedTexSubImage2D, PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC);
		GLLOAD(glCompressedTexSubImage1D, PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC);
		GLLOAD(glGetCompressedTexImage, PFNGLGETCOMPRESSEDTEXIMAGEPROC);
	}

	void LoadGL14()
	{
		GLLOAD(glBlendFuncSeparate, PFNGLBLENDFUNCSEPARATEPROC);
		GLLOAD(glMultiDrawArrays, PFNGLMULTIDRAWARRAYSPROC);
		GLLOAD(glMultiDrawElements, PFNGLMULTIDRAWELEMENTSPROC);
		GLLOAD(glPointParameterf, PFNGLPOINTPARAMETERFPROC);
		GLLOAD(glPointParameterfv, PFNGLPOINTPARAMETERFVPROC);
		GLLOAD(glPointParameteri, PFNGLPOINTPARAMETERIPROC);
		GLLOAD(glPointParameteriv, PFNGLPOINTPARAMETERIVPROC);
		GLLOAD(glBlendColor, PFNGLBLENDCOLORPROC);
		GLLOAD(glBlendEquation, PFNGLBLENDEQUATIONPROC);
	}

	void LoadGL15()
	{
		GLLOAD(glGenQueries, PFNGLGENQUERIESPROC);
		GLLOAD(glDeleteQueries, PFNGLDELETEQUERIESPROC);
		GLLOAD(glIsQuery, PFNGLISQUERYPROC);
		GLLOAD(glBeginQuery, PFNGLBEGINQUERYPROC);
		GLLOAD(glEndQuery, PFNGLENDQUERYPROC);
		GLLOAD(glGetQueryiv, PFNGLGETQUERYIVPROC);
		GLLOAD(glGetQueryObjectiv, PFNGLGETQUERYOBJECTIVPROC);
		GLLOAD(glGetQueryObjectuiv, PFNGLGETQUERYOBJECTUIVPROC);
		GLLOAD(glBindBuffer, PFNGLBINDBUFFERPROC);
		GLLOAD(glDeleteBuffers, PFNGLDELETEBUFFERSPROC);
		GLLOAD(glGenBuffers, PFNGLGENBUFFERSPROC);
		GLLOAD(glIsBuffer, PFNGLISBUFFERPROC);
		GLLOAD(glBufferData, PFNGLBUFFERDATAPROC);
		GLLOAD(glBufferSubData, PFNGLBUFFERSUBDATAPROC);
		GLLOAD(glGetBufferSubData, PFNGLGETBUFFERSUBDATAPROC);
		GLLOAD(glMapBuffer, PFNGLMAPBUFFERPROC);
		GLLOAD(glUnmapBuffer, PFNGLUNMAPBUFFERPROC);
		GLLOAD(glGetBufferParameteriv, PFNGLGETBUFFERPARAMETERIVPROC);
		GLLOAD(glGetBufferPointerv, PFNGLGETBUFFERPOINTERVPROC);
	}

	void LoadGL20()
	{
		GLLOAD(glBlendEquationSeparate, PFNGLBLENDEQUATIONSEPARATEPROC);
		GLLOAD(glDrawBuffers, PFNGLDRAWBUFFERSPROC);
		GLLOAD(glStencilOpSeparate, PFNGLSTENCILOPSEPARATEPROC);
		GLLOAD(glStencilFuncSeparate, PFNGLSTENCILFUNCSEPARATEPROC);
		GLLOAD(glStencilMaskSeparate, PFNGLSTENCILMASKSEPARATEPROC);
		GLLOAD(glAttachShader, PFNGLATTACHSHADERPROC);
		GLLOAD(glBindAttribLocation, PFNGLBINDATTRIBLOCATIONPROC);
		GLLOAD(glCompileShader, PFNGLCOMPILESHADERPROC);
		GLLOAD(glCreateProgram, PFNGLCREATEPROGRAMPROC);
		GLLOAD(glCreateShader, PFNGLCREATESHADERPROC);
		GLLOAD(glDeleteProgram, PFNGLDELETEPROGRAMPROC);
		GLLOAD(glDeleteShader, PFNGLDELETESHADERPROC);
		GLLOAD(glDetachShader, PFNGLDETACHSHADERPROC);
		GLLOAD(glDisableVertexAttribArray, PFNGLDISABLEVERTEXATTRIBARRAYPROC);
		GLLOAD(glEnableVertexAttribArray, PFNGLENABLEVERTEXATTRIBARRAYPROC);
		GLLOAD(glGetActiveAttrib, PFNGLGETACTIVEATTRIBPROC);
		GLLOAD(glGetActiveUniform, PFNGLGETACTIVEUNIFORMPROC);
		GLLOAD(glGetAttachedShaders, PFNGLGETATTACHEDSHADERSPROC);
		GLLOAD(glGetAttribLocation, PFNGLGETATTRIBLOCATIONPROC);
		GLLOAD(glGetProgramiv, PFNGLGETPROGRAMIVPROC);
		GLLOAD(glGetProgramInfoLog, PFNGLGETPROGRAMINFOLOGPROC);
		GLLOAD(glGetShaderiv, PFNGLGETSHADERIVPROC);
		GLLOAD(glGetShaderInfoLog, PFNGLGETSHADERINFOLOGPROC);
		GLLOAD(glGetShaderSource, PFNGLGETSHADERSOURCEPROC);
		GLLOAD(glGetUniformLocation, PFNGLGETUNIFORMLOCATIONPROC);
		GLLOAD(glGetUniformfv, PFNGLGETUNIFORMFVPROC);
		GLLOAD(glGetUniformiv, PFNGLGETUNIFORMIVPROC);
		GLLOAD(glGetVertexAttribdv, PFNGLGETVERTEXATTRIBDVPROC);
		GLLOAD(glGetVertexAttribfv, PFNGLGETVERTEXATTRIBFVPROC);
		GLLOAD(glGetVertexAttribiv, PFNGLGETVERTEXATTRIBIVPROC);
		GLLOAD(glGetVertexAttribPointerv, PFNGLGETVERTEXATTRIBPOINTERVPROC);
		GLLOAD(glIsProgram, PFNGLISPROGRAMPROC);
		GLLOAD(glIsShader, PFNGLISSHADERPROC);
		GLLOAD(glLinkProgram, PFNGLLINKPROGRAMPROC);
		GLLOAD(glShaderSource, PFNGLSHADERSOURCEPROC);
		GLLOAD(glUseProgram, PFNGLUSEPROGRAMPROC);
		GLLOAD(glUniform1f, PFNGLUNIFORM1FPROC);
		GLLOAD(glUniform2f, PFNGLUNIFORM2FPROC);
		GLLOAD(glUniform3f, PFNGLUNIFORM3FPROC);
		GLLOAD(glUniform4f, PFNGLUNIFORM4FPROC);
		GLLOAD(glUniform1i, PFNGLUNIFORM1IPROC);
		GLLOAD(glUniform2i, PFNGLUNIFORM2IPROC);
		GLLOAD(glUniform3i, PFNGLUNIFORM3IPROC);
		GLLOAD(glUniform4i, PFNGLUNIFORM4IPROC);
		GLLOAD(glUniform1fv, PFNGLUNIFORM1FVPROC);
		GLLOAD(glUniform2fv, PFNGLUNIFORM2FVPROC);
		GLLOAD(glUniform3fv, PFNGLUNIFORM3FVPROC);
		GLLOAD(glUniform4fv, PFNGLUNIFORM4FVPROC);
		GLLOAD(glUniform1iv, PFNGLUNIFORM1IVPROC);
		GLLOAD(glUniform2iv, PFNGLUNIFORM2IVPROC);
		GLLOAD(glUniform3iv, PFNGLUNIFORM3IVPROC);
		GLLOAD(glUniform4iv, PFNGLUNIFORM4IVPROC);
		GLLOAD(glUniformMatrix2fv, PFNGLUNIFORMMATRIX2FVPROC);
		GLLOAD(glUniformMatrix3fv, PFNGLUNIFORMMATRIX3FVPROC);
		GLLOAD(glUniformMatrix4fv, PFNGLUNIFORMMATRIX4FVPROC);
		GLLOAD(glValidateProgram, PFNGLVALIDATEPROGRAMPROC);
		GLLOAD(glVertexAttrib1d, PFNGLVERTEXATTRIB1DPROC);
		GLLOAD(glVertexAttrib1dv, PFNGLVERTEXATTRIB1DVPROC);
		GLLOAD(glVertexAttrib1f, PFNGLVERTEXATTRIB1FPROC);
		GLLOAD(glVertexAttrib1fv, PFNGLVERTEXATTRIB1FVPROC);
		GLLOAD(glVertexAttrib1s, PFNGLVERTEXATTRIB1SPROC);
		GLLOAD(glVertexAttrib1sv, PFNGLVERTEXATTRIB1SVPROC);
		GLLOAD(glVertexAttrib2d, PFNGLVERTEXATTRIB2DPROC);
		GLLOAD(glVertexAttrib2dv, PFNGLVERTEXATTRIB2DVPROC);
		GLLOAD(glVertexAttrib2f, PFNGLVERTEXATTRIB2FPROC);
		GLLOAD(glVertexAttrib2fv, PFNGLVERTEXATTRIB2FVPROC);
		GLLOAD(glVertexAttrib2s, PFNGLVERTEXATTRIB2SPROC);
		GLLOAD(glVertexAttrib2sv, PFNGLVERTEXATTRIB2SVPROC);
		GLLOAD(glVertexAttrib3d, PFNGLVERTEXATTRIB3DPROC);
		GLLOAD(glVertexAttrib3dv, PFNGLVERTEXATTRIB3DVPROC);
		GLLOAD(glVertexAttrib3f, PFNGLVERTEXATTRIB3FPROC);
		GLLOAD(glVertexAttrib3fv, PFNGLVERTEXATTRIB3FVPROC);
		GLLOAD(glVertexAttrib3s, PFNGLVERTEXATTRIB3SPROC);
		GLLOAD(glVertexAttrib3sv, PFNGLVERTEXATTRIB3SVPROC);
		GLLOAD(glVertexAttrib4Nbv, PFNGLVERTEXATTRIB4NBVPROC);
		GLLOAD(glVertexAttrib4Niv, PFNGLVERTEXATTRIB4NIVPROC);
		GLLOAD(glVertexAttrib4Nsv, PFNGLVERTEXATTRIB4NSVPROC);
		GLLOAD(glVertexAttrib4Nub, PFNGLVERTEXATTRIB4NUBPROC);
		GLLOAD(glVertexAttrib4Nubv, PFNGLVERTEXATTRIB4NUBVPROC);
		GLLOAD(glVertexAttrib4Nuiv, PFNGLVERTEXATTRIB4NUIVPROC);
		GLLOAD(glVertexAttrib4Nusv, PFNGLVERTEXATTRIB4NUSVPROC);
		GLLOAD(glVertexAttrib4bv, PFNGLVERTEXATTRIB4BVPROC);
		GLLOAD(glVertexAttrib4d, PFNGLVERTEXATTRIB4DPROC);
		GLLOAD(glVertexAttrib4dv, PFNGLVERTEXATTRIB4DVPROC);
		GLLOAD(glVertexAttrib4f, PFNGLVERTEXATTRIB4FPROC);
		GLLOAD(glVertexAttrib4fv, PFNGLVERTEXATTRIB4FVPROC);
		GLLOAD(glVertexAttrib4iv, PFNGLVERTEXATTRIB4IVPROC);
		GLLOAD(glVertexAttrib4s, PFNGLVERTEXATTRIB4SPROC);
		GLLOAD(glVertexAttrib4sv, PFNGLVERTEXATTRIB4SVPROC);
		GLLOAD(glVertexAttrib4ubv, PFNGLVERTEXATTRIB4UBVPROC);
		GLLOAD(glVertexAttrib4uiv, PFNGLVERTEXATTRIB4UIVPROC);
		GLLOAD(glVertexAttrib4usv, PFNGLVERTEXATTRIB4USVPROC);
		GLLOAD(glVertexAttribPointer, PFNGLVERTEXATTRIBPOINTERPROC);
	}

	void LoadGL21()
	{
		GLLOAD(glUniformMatrix2x3fv, PFNGLUNIFORMMATRIX2X3FVPROC);
		GLLOAD(glUniformMatrix3x2fv, PFNGLUNIFORMMATRIX3X2FVPROC);
		GLLOAD(glUniformMatrix2x4fv, PFNGLUNIFORMMATRIX2X4FVPROC);
		GLLOAD(glUniformMatrix4x2fv, PFNGLUNIFORMMATRIX4X2FVPROC);
		GLLOAD(glUniformMatrix3x4fv, PFNGLUNIFORMMATRIX3X4FVPROC);
		GLLOAD(glUniformMatrix4x3fv, PFNGLUNIFORMMATRIX4X3FVPROC);
	}

	void LoadGL30()
	{
		GLLOAD(glColorMaski, PFNGLCOLORMASKIPROC);
		GLLOAD(glGetBooleani_v, PFNGLGETBOOLEANI_VPROC);
		GLLOAD(glGetIntegeri_v, PFNGLGETINTEGERI_VPROC);
		GLLOAD(glEnablei, PFNGLENABLEIPROC);
		GLLOAD(glDisablei, PFNGLDISABLEIPROC);
		GLLOAD(glIsEnabledi, PFNGLISENABLEDIPROC);
		GLLOAD(glBeginTransformFeedback, PFNGLBEGINTRANSFORMFEEDBACKPROC);
		GLLOAD(glEndTransformFeedback, PFNGLENDTRANSFORMFEEDBACKPROC);
		GLLOAD(glBindBufferRange, PFNGLBINDBUFFERRANGEPROC);
		GLLOAD(glBindBufferBase, PFNGLBINDBUFFERBASEPROC);
		GLLOAD(glTransformFeedbackVaryings, PFNGLTRANSFORMFEEDBACKVARYINGSPROC);
		GLLOAD(glGetTransformFeedbackVarying, PFNGLGETTRANSFORMFEEDBACKVARYINGPROC);
		GLLOAD(glClampColor, PFNGLCLAMPCOLORPROC);
		GLLOAD(glBeginConditionalRender, PFNGLBEGINCONDITIONALRENDERPROC);
		GLLOAD(glEndConditionalRender, PFNGLENDCONDITIONALRENDERPROC);
		GLLOAD(glVertexAttribIPointer, PFNGLVERTEXATTRIBIPOINTERPROC);
		GLLOAD(glGetVertexAttribIiv, PFNGLGETVERTEXATTRIBIIVPROC);
		GLLOAD(glGetVertexAttribIuiv, PFNGLGETVERTEXATTRIBIUIVPROC);
		GLLOAD(glVertexAttribI1i, PFNGLVERTEXATTRIBI1IPROC);
		GLLOAD(glVertexAttribI2i, PFNGLVERTEXATTRIBI2IPROC);
		GLLOAD(glVertexAttribI3i, PFNGLVERTEXATTRIBI3IPROC);
		GLLOAD(glVertexAttribI4i, PFNGLVERTEXATTRIBI4IPROC);
		GLLOAD(glVertexAttribI1ui, PFNGLVERTEXATTRIBI1UIPROC);
		GLLOAD(glVertexAttribI2ui, PFNGLVERTEXATTRIBI2UIPROC);
		GLLOAD(glVertexAttribI3ui, PFNGLVERTEXATTRIBI3UIPROC);
		GLLOAD(glVertexAttribI4ui, PFNGLVERTEXATTRIBI4UIPROC);
		GLLOAD(glVertexAttribI1iv, PFNGLVERTEXATTRIBI1IVPROC);
		GLLOAD(glVertexAttribI2iv, PFNGLVERTEXATTRIBI2IVPROC);
		GLLOAD(glVertexAttribI3iv, PFNGLVERTEXATTRIBI3IVPROC);
		GLLOAD(glVertexAttribI4iv, PFNGLVERTEXATTRIBI4IVPROC);
		GLLOAD(glVertexAttribI1uiv, PFNGLVERTEXATTRIBI1UIVPROC);
		GLLOAD(glVertexAttribI2uiv, PFNGLVERTEXATTRIBI2UIVPROC);
		GLLOAD(glVertexAttribI3uiv, PFNGLVERTEXATTRIBI3UIVPROC);
		GLLOAD(glVertexAttribI4uiv, PFNGLVERTEXATTRIBI4UIVPROC);
		GLLOAD(glVertexAttribI4bv, PFNGLVERTEXATTRIBI4BVPROC);
		GLLOAD(glVertexAttribI4sv, PFNGLVERTEXATTRIBI4SVPROC);
		GLLOAD(glVertexAttribI4ubv, PFNGLVERTEXATTRIBI4UBVPROC);
		GLLOAD(glVertexAttribI4usv, PFNGLVERTEXATTRIBI4USVPROC);
		GLLOAD(glGetUniformuiv, PFNGLGETUNIFORMUIVPROC);
		GLLOAD(glBindFragDataLocation, PFNGLBINDFRAGDATALOCATIONPROC);
		GLLOAD(glGetFragDataLocation, PFNGLGETFRAGDATALOCATIONPROC);
		GLLOAD(glUniform1ui, PFNGLUNIFORM1UIPROC);
		GLLOAD(glUniform2ui, PFNGLUNIFORM2UIPROC);
		GLLOAD(glUniform3ui, PFNGLUNIFORM3UIPROC);
		GLLOAD(glUniform4ui, PFNGLUNIFORM4UIPROC);
		GLLOAD(glUniform1uiv, PFNGLUNIFORM1UIVPROC);
		GLLOAD(glUniform2uiv, PFNGLUNIFORM2UIVPROC);
		GLLOAD(glUniform3uiv, PFNGLUNIFORM3UIVPROC);
		GLLOAD(glUniform4uiv, PFNGLUNIFORM4UIVPROC);
		GLLOAD(glTexParameterIiv, PFNGLTEXPARAMETERIIVPROC);
		GLLOAD(glTexParameterIuiv, PFNGLTEXPARAMETERIUIVPROC);
		GLLOAD(glGetTexParameterIiv, PFNGLGETTEXPARAMETERIIVPROC);
		GLLOAD(glGetTexParameterIuiv, PFNGLGETTEXPARAMETERIUIVPROC);
		GLLOAD(glClearBufferiv, PFNGLCLEARBUFFERIVPROC);
		GLLOAD(glClearBufferuiv, PFNGLCLEARBUFFERUIVPROC);
		GLLOAD(glClearBufferfv, PFNGLCLEARBUFFERFVPROC);
		GLLOAD(glClearBufferfi, PFNGLCLEARBUFFERFIPROC);
		GLLOAD(glGetStringi, PFNGLGETSTRINGIPROC);
		GLLOAD(glIsRenderbuffer, PFNGLISRENDERBUFFERPROC);
		GLLOAD(glBindRenderbuffer, PFNGLBINDRENDERBUFFERPROC);
		GLLOAD(glDeleteRenderbuffers, PFNGLDELETERENDERBUFFERSPROC);
		GLLOAD(glGenRenderbuffers, PFNGLGENRENDERBUFFERSPROC);
		GLLOAD(glRenderbufferStorage, PFNGLRENDERBUFFERSTORAGEPROC);
		GLLOAD(glGetRenderbufferParameteriv, PFNGLGETRENDERBUFFERPARAMETERIVPROC);
		GLLOAD(glIsFramebuffer, PFNGLISFRAMEBUFFERPROC);
		GLLOAD(glBindFramebuffer, PFNGLBINDFRAMEBUFFERPROC);
		GLLOAD(glDeleteFramebuffers, PFNGLDELETEFRAMEBUFFERSPROC);
		GLLOAD(glGenFramebuffers, PFNGLGENFRAMEBUFFERSPROC);
		GLLOAD(glCheckFramebufferStatus, PFNGLCHECKFRAMEBUFFERSTATUSPROC);
		GLLOAD(glFramebufferTexture1D, PFNGLFRAMEBUFFERTEXTURE1DPROC);
		GLLOAD(glFramebufferTexture2D, PFNGLFRAMEBUFFERTEXTURE2DPROC);
		GLLOAD(glFramebufferTexture3D, PFNGLFRAMEBUFFERTEXTURE3DPROC);
		GLLOAD(glFramebufferRenderbuffer, PFNGLFRAMEBUFFERRENDERBUFFERPROC);
		GLLOAD(glGetFramebufferAttachmentParameteriv, PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC);
		GLLOAD(glGenerateMipmap, PFNGLGENERATEMIPMAPPROC);
		GLLOAD(glBlitFramebuffer, PFNGLBLITFRAMEBUFFERPROC);
		GLLOAD(glRenderbufferStorageMultisample, PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC);
		GLLOAD(glFramebufferTextureLayer, PFNGLFRAMEBUFFERTEXTURELAYERPROC);
		GLLOAD(glMapBufferRange, PFNGLMAPBUFFERRANGEPROC);
		GLLOAD(glFlushMappedBufferRange, PFNGLFLUSHMAPPEDBUFFERRANGEPROC);
		GLLOAD(glBindVertexArray, PFNGLBINDVERTEXARRAYPROC);
		GLLOAD(glDeleteVertexArrays, PFNGLDELETEVERTEXARRAYSPROC);
		GLLOAD(glGenVertexArrays, PFNGLGENVERTEXARRAYSPROC);
		GLLOAD(glIsVertexArray, PFNGLISVERTEXARRAYPROC);
	}

	void LoadGL31()
	{
		GLLOAD(glDrawArraysInstanced, PFNGLDRAWARRAYSINSTANCEDPROC);
		GLLOAD(glDrawElementsInstanced, PFNGLDRAWELEMENTSINSTANCEDPROC);
		GLLOAD(glTexBuffer, PFNGLTEXBUFFERPROC);
		GLLOAD(glPrimitiveRestartIndex, PFNGLPRIMITIVERESTARTINDEXPROC);
		GLLOAD(glCopyBufferSubData, PFNGLCOPYBUFFERSUBDATAPROC);
		GLLOAD(glGetUniformIndices, PFNGLGETUNIFORMINDICESPROC);
		GLLOAD(glGetActiveUniformsiv, PFNGLGETACTIVEUNIFORMSIVPROC);
		GLLOAD(glGetActiveUniformName, PFNGLGETACTIVEUNIFORMNAMEPROC);
		GLLOAD(glGetUniformBlockIndex, PFNGLGETUNIFORMBLOCKINDEXPROC);
		GLLOAD(glGetActiveUniformBlockiv, PFNGLGETACTIVEUNIFORMBLOCKIVPROC);
		GLLOAD(glGetActiveUniformBlockName, PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC);
		GLLOAD(glUniformBlockBinding, PFNGLUNIFORMBLOCKBINDINGPROC);
	}

	void LoadGL32()
	{
		GLLOAD(glDrawElementsBaseVertex, PFNGLDRAWELEMENTSBASEVERTEXPROC);
		GLLOAD(glDrawRangeElementsBaseVertex, PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC);
		GLLOAD(glDrawElementsInstancedBaseVertex, PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC);
		GLLOAD(glMultiDrawElementsBaseVertex, PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC);
		GLLOAD(glProvokingVertex, PFNGLPROVOKINGVERTEXPROC);
		GLLOAD(glFenceSync, PFNGLFENCESYNCPROC);
		GLLOAD(glIsSync, PFNGLISSYNCPROC);
		GLLOAD(glDeleteSync, PFNGLDELETESYNCPROC);
		GLLOAD(glClientWaitSync, PFNGLCLIENTWAITSYNCPROC);
		GLLOAD(glWaitSync, PFNGLWAITSYNCPROC);
		GLLOAD(glGetInteger64v, PFNGLGETINTEGER64VPROC);
		GLLOAD(glGetSynciv, PFNGLGETSYNCIVPROC);
		GLLOAD(glGetInteger64i_v, PFNGLGETINTEGER64I_VPROC);
		GLLOAD(glGetBufferParameteri64v, PFNGLGETBUFFERPARAMETERI64VPROC);
		GLLOAD(glFramebufferTexture, PFNGLFRAMEBUFFERTEXTUREPROC);
		GLLOAD(glTexImage2DMultisample, PFNGLTEXIMAGE2DMULTISAMPLEPROC);
		GLLOAD(glTexImage3DMultisample, PFNGLTEXIMAGE3DMULTISAMPLEPROC);
		GLLOAD(glGetMultisamplefv, PFNGLGETMULTISAMPLEFVPROC);
		GLLOAD(glSampleMaski, PFNGLSAMPLEMASKIPROC);
	}

	void LoadGL33()
	{
		GLLOAD(glBindFragDataLocationIndexed, PFNGLBINDFRAGDATALOCATIONINDEXEDPROC);
		GLLOAD(glGetFragDataIndex, PFNGLGETFRAGDATAINDEXPROC);
		GLLOAD(glGenSamplers, PFNGLGENSAMPLERSPROC);
		GLLOAD(glDeleteSamplers, PFNGLDELETESAMPLERSPROC);
		GLLOAD(glIsSampler, PFNGLISSAMPLERPROC);
		GLLOAD(glBindSampler, PFNGLBINDSAMPLERPROC);
		GLLOAD(glSamplerParameteri, PFNGLSAMPLERPARAMETERIPROC);
		GLLOAD(glSamplerParameteriv, PFNGLSAMPLERPARAMETERIVPROC);
		GLLOAD(glSamplerParameterf, PFNGLSAMPLERPARAMETERFPROC);
		GLLOAD(glSamplerParameterfv, PFNGLSAMPLERPARAMETERFVPROC);
		GLLOAD(glSamplerParameterIiv, PFNGLSAMPLERPARAMETERIIVPROC);
		GLLOAD(glSamplerParameterIuiv, PFNGLSAMPLERPARAMETERIUIVPROC);
		GLLOAD(glGetSamplerParameteriv, PFNGLGETSAMPLERPARAMETERIVPROC);
		GLLOAD(glGetSamplerParameterIiv, PFNGLGETSAMPLERPARAMETERIIVPROC);
		GLLOAD(glGetSamplerParameterfv, PFNGLGETSAMPLERPARAMETERFVPROC);
		GLLOAD(glGetSamplerParameterIuiv, PFNGLGETSAMPLERPARAMETERIUIVPROC);
		GLLOAD(glQueryCounter, PFNGLQUERYCOUNTERPROC);
		GLLOAD(glGetQueryObjecti64v, PFNGLGETQUERYOBJECTI64VPROC);
		GLLOAD(glGetQueryObjectui64v, PFNGLGETQUERYOBJECTUI64VPROC);
		GLLOAD(glVertexAttribDivisor, PFNGLVERTEXATTRIBDIVISORPROC);
		GLLOAD(glVertexAttribP1ui, PFNGLVERTEXATTRIBP1UIPROC);
		GLLOAD(glVertexAttribP1uiv, PFNGLVERTEXATTRIBP1UIVPROC);
		GLLOAD(glVertexAttribP2ui, PFNGLVERTEXATTRIBP2UIPROC);
		GLLOAD(glVertexAttribP2uiv, PFNGLVERTEXATTRIBP2UIVPROC);
		GLLOAD(glVertexAttribP3ui, PFNGLVERTEXATTRIBP3UIPROC);
		GLLOAD(glVertexAttribP3uiv, PFNGLVERTEXATTRIBP3UIVPROC);
		GLLOAD(glVertexAttribP4ui, PFNGLVERTEXATTRIBP4UIPROC);
		GLLOAD(glVertexAttribP4uiv, PFNGLVERTEXATTRIBP4UIVPROC);
	}

	bool LoadGLMethods()
	{
		// Create a window as usual

		const std::wstring DUMMY_CLASS = L"DummyCls";

		WNDCLASS dummy{};
		dummy.lpfnWndProc = DefWindowProc;
		dummy.lpszClassName = DUMMY_CLASS.c_str();
		dummy.hInstance = GetModuleHandle(nullptr);
		dummy.style = CS_OWNDC;

		if (!RegisterClass(&dummy))
		{
			std::cout << "Failed to register class dummy: " << GetLastError() << "\n";
			return false;
		};

		HWND window = CreateWindowEx(
			0,
			DUMMY_CLASS.c_str(),
			L"Dummy",
			WS_OVERLAPPEDWINDOW,
			CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT,
			nullptr, nullptr, GetModuleHandle(nullptr), nullptr
		);

		if (!window)
		{
			std::cout << "Failed to create dummy window!: " << GetLastError() << "\n";
			return false;
		}

		// Define a temp pixelformat for this gl context
		PIXELFORMATDESCRIPTOR pixelFormatDescriptor
		{
			sizeof(PIXELFORMATDESCRIPTOR),
			1,
			PFD_DRAW_TO_WINDOW | PFD_SUPPORT_OPENGL | PFD_DOUBLEBUFFER,
			PFD_TYPE_RGBA,
			32,
			0, 0, 0, 0, 0, 0, 0, 0,
			0, 0, 0, 0, 0,
			24, 8, 0,
			PFD_MAIN_PLANE,
			0, 0, 0, 0
		};

		// Let windows choose a pixel format
		HDC deviceContext = GetDC(window);
		int pixelFormat = ChoosePixelFormat(deviceContext, &pixelFormatDescriptor);

		if (!pixelFormat)
		{
			std::cout << "Failed to find a pixel format for this descriptor: " << GetLastError() << "\n";
			return false;
		}

		// Set the pixel format
		BOOL pixelFormatChosen = SetPixelFormat(deviceContext, pixelFormat, &pixelFormatDescriptor);
		if (!pixelFormatChosen)
		{
			std::cout << "Failed to set the specified pixel format!: " << GetLastError() << "\n";
			return false;
		}

		// Create the GL context
		HGLRC glContext = wglCreateContext(deviceContext);
		wglMakeCurrent(deviceContext, glContext);

		GLLOAD(wglCreateContextAttribsARB, PFNGLCREATECONTEXTARBPROC);
		GLLOAD(wglChoosePixelFormatARB, PFNGLCHOOSEPIXELFORMATARBPROC);

		LoadGL12();
		LoadGL13();
		LoadGL14();
		LoadGL15();
		LoadGL20();
		LoadGL21();
		LoadGL30();
		LoadGL31();
		LoadGL32();
		LoadGL33();

		wglMakeCurrent(deviceContext, NULL);
		wglDeleteContext(glContext);
		DestroyWindow(window);

		return true;
	}
	
}